FROM mysql:5.7
MAINTAINER w2casti@gmail.com

#ADD /code/data/tng*.sql /code/ 

# copy initial db
COPY tng-20170524-2310PM.sql /docker-entrypoint-initdb.d/db.sql

# Change to working directory
#WORKDIR code


